// AudioWorklet processor generated by github.com/ebitengine/oto/v3 v3.4.0
// (driver_js.go) for 2048 frames and 2 channels. Fixture for audio-headroom.test.cjs.
class OtoWorkletProcessor extends AudioWorkletProcessor {
	constructor() {
		super();
		this.bufferSize_ = 2048;
		this.channelCount_ = 2;
		this.buf_ = new Float32Array();
		this.waitRecv_ = false;

		// Receive data from the main thread.
		this.port.onmessage = (event) => {
			const buf = event.data;
			const newBuf = new Float32Array(this.buf_.length + buf.length);
			newBuf.set(this.buf_);
			newBuf.set(buf, this.buf_.length);
			this.buf_ = newBuf;
			this.waitRecv_ = false;
		}
	}

	process(inputs, outputs, parameters) {
		const output = outputs[0];

		// If the buffer is too short, request more data and return silence.
		if (this.buf_.length < output[0].length*this.channelCount_) {
			if (!this.waitRecv_) {
				this.waitRecv_ = true;
				this.port.postMessage(null);
			}
			for (let i = 0; i < output.length; i++) {
				output[i].fill(0);
			}
			return true;
		}

		// If the buffer is short, request more data.
		if (this.buf_.length < this.bufferSize_*this.channelCount_ / 2 && !this.waitRecv_) {
			this.waitRecv_ = true;
			this.port.postMessage(null);
		}

		for (let i = 0; i < this.channelCount_; i++) {
			for (let j = 0; j < output[i].length; j++) {
				output[i][j] = this.buf_[j*this.channelCount_+i];
			}
		}
		this.buf_ = this.buf_.slice(output[0].length*this.channelCount_);
		return true;
	}
}
registerProcessor('oto-worklet-processor', OtoWorkletProcessor);
